// Activity word deck: point value (3/4/5) = difficulty; every word must work for drawing, describing and acting.
export const WORDS = {
  en: {
    3: [
      "cat", "dog", "fish", "bird", "horse", "cow", "pig", "duck", "rabbit", "mouse",
      "lion", "elephant", "giraffe", "monkey", "frog", "spider", "bee", "butterfly", "snake", "sheep",
      "chicken", "bear", "owl", "turtle", "shark", "apple", "banana", "cake", "pizza", "egg",
      "bread", "cheese", "ice cream", "carrot", "sandwich", "milk", "cookie", "lemon", "grapes", "hot dog",
      "bicycle", "toothbrush", "chair", "table", "book", "phone", "ball", "shoe", "hat", "clock",
      "key", "door", "window", "bed", "cup", "spoon", "fork", "knife", "umbrella", "glasses",
      "scissors", "pencil", "comb", "bucket", "candle", "balloon", "kite", "sock", "lamp", "mirror",
      "pillow", "broom", "ladder", "bottle", "backpack", "sun", "moon", "star", "rain", "snow",
      "cloud", "tree", "flower", "rainbow", "mountain", "fire", "leaf", "river", "car", "boat",
      "train", "airplane", "bus", "rocket", "tractor", "guitar", "drum", "piano", "baby", "teacher",
      "doctor", "king", "clown", "house", "school", "beach", "bridge", "swim", "run", "jump",
      "sleep", "eat", "drink", "cry", "laugh", "dance", "sing", "read", "write", "clap",
      "wave", "throw", "kick", "walk", "climb", "cook", "sit", "push", "smile", "knock",
      "paint", "drive", "dig", "yawn", "fly", "hug", "wash hands", "football", "tennis", "ghost",
      "robot", "crown", "heart", "tooth", "hand", "nose", "ear", "eye", "foot", "hair",
    ],
    4: [
      "lighthouse", "vacuum cleaner", "sneeze", "firefighter", "snowman", "penguin", "kangaroo", "octopus", "crocodile", "dolphin",
      "zebra", "camel", "parrot", "squirrel", "hedgehog", "bat", "whale", "peacock", "jellyfish", "snail",
      "flamingo", "gorilla", "deer", "ostrich", "woodpecker", "pilot", "astronaut", "dentist", "police officer", "chef",
      "farmer", "hairdresser", "magician", "waiter", "painter", "mechanic", "plumber", "lifeguard", "photographer", "postman",
      "nurse", "judge", "builder", "scientist", "pirate", "cowboy", "knight", "detective", "microscope", "telescope",
      "parachute", "wheelbarrow", "hammock", "typewriter", "lawn mower", "hair dryer", "washing machine", "fire extinguisher", "compass", "anchor",
      "treasure chest", "magnifying glass", "stethoscope", "skateboard", "helmet", "suitcase", "wheelchair", "headphones", "sunglasses", "toaster",
      "rolling pin", "frying pan", "sewing machine", "kettle", "castle", "volcano", "island", "desert", "igloo", "circus",
      "museum", "hospital", "airport", "playground", "zoo", "library", "waterfall", "cave", "farm", "swimming pool",
      "windmill", "tent", "jungle", "juggle", "knit", "snore", "hiccup", "whisper", "shiver", "sweep",
      "ironing", "surf", "tiptoe", "sunbathe", "blow bubbles", "rowing", "milk a cow", "tie shoelaces", "take a selfie", "sneak",
      "hitchhike", "arm wrestling", "pillow fight", "skiing", "ice skating", "boxing", "archery", "golf", "basketball", "volleyball",
      "karate", "diving", "fishing", "weightlifting", "bowling", "horse riding", "gymnastics", "table tennis", "scarecrow", "dragon",
      "mermaid", "vampire", "witch", "superhero", "unicorn", "alien", "dinosaur", "fireworks", "birthday party", "wedding",
      "camping", "picnic", "tornado", "thunderstorm", "sandcastle", "popcorn", "spaghetti", "pancake", "sushi", "earthquake",
    ],
    5: [
      "Eiffel Tower", "Statue of Liberty", "Tower of Pisa", "Great Wall", "pyramids", "Big Ben", "Mona Lisa", "Colosseum", "Stonehenge", "Taj Mahal",
      "Mount Everest", "Niagara Falls", "Golden Gate Bridge", "Mount Rushmore", "North Pole", "Sydney Opera House", "Christ the Redeemer", "Robin Hood", "Titanic", "Harry Potter",
      "Sherlock Holmes", "Cinderella", "Snow White", "Pinocchio", "Dracula", "Frankenstein", "Tarzan", "Santa Claus", "Red Riding Hood", "Peter Pan",
      "King Kong", "Easter Bunny", "tooth fairy", "Robinson Crusoe", "Captain Hook", "Noah's Ark", "Romeo and Juliet", "Hercules", "Medusa", "Trojan horse",
      "Aladdin", "Rapunzel", "Sleeping Beauty", "Charlie Chaplin", "Napoleon", "Cleopatra", "Einstein", "Mozart", "jealousy", "déjà vu",
      "time travel", "homesick", "traffic jam", "nostalgia", "freedom", "gravity", "echo", "silence", "bad luck", "friendship",
      "revenge", "curiosity", "boredom", "stage fright", "jet lag", "midlife crisis", "daydreaming", "sleepwalking", "patience", "surprise party",
      "blind date", "broken heart", "cold feet", "piece of cake", "white lie", "brainstorm", "fear of heights", "hide and seek", "tug of war", "musical chairs",
      "domino effect", "butterfly effect", "black hole", "solar eclipse", "northern lights", "evolution", "invisibility", "teleportation", "zero gravity", "ghost town",
      "haunted house", "treasure hunt", "midnight snack", "spring cleaning", "sore loser", "early bird", "night owl", "couch potato", "bookworm", "sweet tooth",
      "last minute", "rush hour", "happy ending", "cliffhanger", "fairy tale", "lullaby", "nightmare", "tightrope walker", "ventriloquist", "lumberjack",
      "beekeeper", "snake charmer", "bodyguard", "stuntman", "archaeologist", "sculptor", "conductor", "referee", "fortune teller", "hypnotist",
      "sumo wrestling", "bungee jumping", "skydiving", "synchronized swimming", "pole vault", "fencing", "curling", "marathon", "relay race", "penalty kick",
      "Olympic Games", "world record", "red carpet", "standing ovation", "autograph", "paparazzi", "wedding proposal", "honeymoon", "retirement", "graduation",
      "job interview", "lottery", "moving house", "speed limit", "power cut", "seasickness", "reflection", "brain freeze", "procrastination", "sixth sense",
    ],
  },
  sl: {
    3: [
      "mačka", "pes", "riba", "ptica", "konj", "krava", "prašič", "raca", "zajec", "miš",
      "lev", "slon", "žirafa", "opica", "žaba", "pajek", "čebela", "metulj", "kača", "ovca",
      "kokoš", "medved", "sova", "želva", "polž", "jabolko", "banana", "torta", "pica", "jajce",
      "kruh", "sir", "sladoled", "korenje", "mleko", "piškot", "limona", "grozdje", "hruška", "jagoda",
      "palačinka", "lubenica", "hrenovka", "potica", "krof", "kolo", "zobna ščetka", "stol", "miza", "knjiga",
      "telefon", "žoga", "čevelj", "klobuk", "ura", "ključ", "vrata", "okno", "postelja", "skodelica",
      "žlica", "vilica", "nož", "dežnik", "očala", "škarje", "svinčnik", "glavnik", "vedro", "sveča",
      "balon", "papirnati zmaj", "nogavica", "svetilka", "ogledalo", "blazina", "metla", "lestev", "steklenica", "nahrbtnik",
      "sonce", "luna", "zvezda", "dež", "sneg", "oblak", "drevo", "roža", "mavrica", "gora",
      "ogenj", "list", "reka", "avto", "čoln", "vlak", "letalo", "avtobus", "raketa", "traktor",
      "kitara", "boben", "klavir", "harmonika", "dojenček", "učitelj", "zdravnik", "kralj", "klovn", "hiša",
      "šola", "plaža", "most", "plavati", "teči", "skakati", "spati", "jesti", "piti", "jokati",
      "smejati se", "plesati", "peti", "brati", "pisati", "ploskati", "mahati", "metati", "brcati", "hoditi",
      "plezati", "kuhati", "sedeti", "potiskati", "nasmehniti se", "trkati", "barvati", "voziti", "smučati", "zehati",
      "leteti", "objemati", "umivati roke", "nogomet", "duh", "robot", "krona", "srce", "zob", "nos",
    ],
    4: [
      "Triglav", "Blejski otok", "kozolec", "čebelnjak", "kurent", "lipicanec", "kranjska klobasa", "čebelar", "dedek Mraz", "Miklavž",
      "parkelj", "pirhi", "jaslice", "kres", "gibanica", "kremšnita", "pršut", "soline", "planinska koča", "smučarski skoki",
      "maškare", "trgatev", "pingvin", "kenguru", "hobotnica", "krokodil", "delfin", "zebra", "kamela", "papiga",
      "veverica", "jež", "netopir", "kit", "pav", "meduza", "gams", "kozorog", "štorklja", "polh",
      "pilot", "astronavt", "zobozdravnik", "policist", "kuhar", "kmet", "frizer", "čarovnik", "natakar", "slikar",
      "mehanik", "reševalec iz vode", "fotograf", "poštar", "medicinska sestra", "sodnik", "znanstvenik", "pirat", "kavboj", "vitez",
      "detektiv", "gasilec", "svetilnik", "sesalnik", "mikroskop", "daljnogled", "padalo", "samokolnica", "viseča mreža", "pisalni stroj",
      "kosilnica", "sušilnik za lase", "pralni stroj", "gasilni aparat", "kompas", "sidro", "skrinja z zakladom", "povečevalno steklo", "rolka", "čelada",
      "kovček", "invalidski voziček", "slušalke", "sončna očala", "ponev", "šivalni stroj", "grad", "ognjenik", "puščava", "iglu",
      "cirkus", "muzej", "bolnišnica", "letališče", "živalski vrt", "knjižnica", "slap", "jama", "kmetija", "bazen",
      "mlin na veter", "šotor", "džungla", "kihati", "žonglirati", "plesti", "smrčati", "kolcati", "šepetati", "drgetati",
      "pometati", "likati", "deskati", "hoditi po prstih", "sončiti se", "pihati milne mehurčke", "veslati", "molsti kravo", "zavezovati vezalke", "štopati",
      "obešati perilo", "drsanje", "boks", "lokostrelstvo", "golf", "košarka", "odbojka", "potapljanje", "ribarjenje", "jahanje",
      "kegljanje", "snežak", "strašilo", "zmaj", "morska deklica", "vampir", "čarovnica", "superjunak", "samorog", "vesoljček",
      "dinozaver", "ognjemet", "rojstni dan", "poroka", "piknik", "tornado", "nevihta", "grad iz peska", "kokice", "potres",
    ],
    5: [
      "Postojnska jama", "človeška ribica", "Prešeren", "kolovrat", "Ljubljanski grad", "Tromostovje", "Zmajski most", "Predjamski grad", "Aljažev stolp", "Planica",
      "Velika planina", "Škocjanske jame", "Martin Krpan", "Kekec", "Peter Klepec", "Kralj Matjaž", "Zlatorog", "Povodni mož", "Piran", "kurentovanje",
      "idrijska čipka", "panjska končnica", "valeta", "Zdravljica", "butara", "dimnikar", "Mojca Pokrajculja", "Eifflov stolp", "Kip svobode", "stolp v Pisi",
      "Kitajski zid", "piramide", "Big Ben", "Mona Lisa", "Kolosej", "Tadž Mahal", "Mount Everest", "Niagarski slapovi", "Titanik", "severni tečaj",
      "Robin Hood", "Harry Potter", "Sherlock Holmes", "Pepelka", "Sneguljčica", "Ostržek", "Drakula", "Frankenstein", "Tarzan", "Rdeča kapica",
      "Peter Pan", "King Kong", "zobna vila", "Robinson Crusoe", "kapitan Kljuka", "Noetova barka", "Romeo in Julija", "Herkul", "trojanski konj", "Aladin",
      "Motovilka", "Trnuljčica", "Charlie Chaplin", "Napoleon", "Kleopatra", "Einstein", "Mozart", "Janko in Metka", "Mali princ", "Pika Nogavička",
      "ljubosumje", "déjà vu", "potovanje v času", "domotožje", "prometni zamašek", "nostalgija", "svoboda", "odmev", "tišina", "smola",
      "prijateljstvo", "maščevanje", "radovednost", "dolgčas", "trema", "sanjarjenje", "mesečnik", "potrpežljivost", "zabava presenečenja", "zmenek na slepo",
      "strto srce", "nedolžna laž", "možganska nevihta", "strah pred višino", "skrivalnice", "vlečenje vrvi", "igra stolčkov", "učinek domin", "črna luknja", "sončni mrk",
      "severni sij", "nevidnost", "teleportacija", "breztežnost", "mesto duhov", "hiša strahov", "lov na zaklad", "nočna ptica", "knjižni molj", "sladkosned",
      "prometna konica", "srečen konec", "pravljica", "uspavanka", "nočna mora", "vrvohodec", "trebušni govornik", "drvar", "krotilec kač", "kaskader",
      "arheolog", "kipar", "dirigent", "vedeževalka", "hipnotizer", "skok z elastiko", "padalstvo", "sinhrono plavanje", "skok s palico", "maraton",
      "štafeta", "enajstmetrovka", "olimpijske igre", "svetovni rekord", "rdeča preproga", "stoječe ovacije", "avtogram", "paparaci", "snubljenje", "medeni tedni",
      "zaposlitveni razgovor", "omejitev hitrosti", "izpad elektrike", "morska bolezen", "odlašanje", "vleči za nos", "biti na trnih", "gradovi v oblakih", "prodajati zijala", "šivanka v senu",
    ],
  },
};
